# Machin Learning Spring1400
## Homework1 / Question 6
#### Mohammad Naseri (810100486)

<hr>

### NAIVE BAYES CLASSIFIER (SELF-DEVELOPED)


### Import Libraires

In [310]:
import pandas as pd
import math
import random

### Import dataset

In [311]:
# load the file and store it in dataset 
dataset = pd.read_csv('./Iris.csv')
dataset

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

### Transform class names to id

In [312]:
def class2id(dataset):
    classes = dataset.Class.values.tolist()
    ids = []
    for i in range(len(classes)):
        if classes[i] not in ids:
            ids.append(classes[i])
    class_ids = []      
    for i in range(len(ids)):
        for j in range(len(classes)):
            if classes[j] == ids[i]:
                class_ids.append(i)
    dataset["Class_id"] = class_ids
    return dataset

In [313]:
dataset = class2id(dataset)
dataset

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width           Class  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

     Class_id  
0           0  
1           0  
2           0  
3           0  
4           0  
..        ...  
145         2  
146         2  
147         2  
148         2  
149         2  

[150 rows x 6 columns]

### Transform Dataframe to id for easier usage
labels are saved in last element of array for easier use

In [314]:
X = dataset[["Sepal_Length","Sepal_Width","Petal_Length","Petal_Width"]].values.tolist()
y = dataset.Class_id.values.tolist()
y

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

### Split data to train and test datasets

In [315]:
def train_test_split(X, y, percentage):
    count = int(len(X) * percentage)
    X_train = []
    X_test = []
    y_train = []
    y_test = []
    X_test = list(X)
    y_test = list(y)
    while len(X_train) < count:
        index = random.randrange(len(X_test))
        X_train.append(X_test.pop(index))
        y_train.append(y_test.pop(index))
    return X_train, X_test, y_train, y_test

In [316]:
ratio = 0.6
X_train, X_test, y_train, y_test = train_test_split(X, y, ratio)
print("TRAIN: \n", pd.DataFrame(X_train, columns=["Sepal_Length","Sepal_Width","Petal_Length","Petal_Width"]))
print("TEST: \n", pd.DataFrame(X_test, columns=["Sepal_Length","Sepal_Width","Petal_Length","Petal_Width"]))
print('Total number of examples are: ', len(X))
print('Out of these, training examples are: ', len(X_train))
print("Test examples are: ", len(X_test))

TRAIN: 
     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0            6.0          2.7           5.1          1.6
1            4.6          3.6           1.0          0.2
2            4.7          3.2           1.3          0.2
3            6.0          3.4           4.5          1.6
4            4.4          3.2           1.3          0.2
..           ...          ...           ...          ...
85           5.7          3.8           1.7          0.3
86           4.9          2.5           4.5          1.7
87           4.4          2.9           1.4          0.2
88           6.3          2.9           5.6          1.8
89           5.1          3.5           1.4          0.3

[90 rows x 4 columns]
TEST: 
     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.6          3.1           1.5          0.2
3            5.0          3.6           1.4     

### Probabilistic functions

In [317]:
def mean(numbers):
    return sum(numbers) / float(len(numbers))

def std_dev(numbers):
    avg = mean(numbers)
    variance = sum([pow(x - avg, 2) for x in numbers]) / float(len(numbers) - 1)
    return math.sqrt(variance)
 
def mean_StdDev(dataset):
    info = [(mean(attribute), std_dev(attribute)) for attribute in zip(*dataset)]
    return info

### Model Proibabilistic fitting

In [318]:
def grouping(X, y):
      groups_dict = {}
      for i in range(len(X)):
          if (y[i] not in groups_dict):
              groups_dict[y[i]] = []
          groups_dict[y[i]].append(X[i])
      return groups_dict

def fit(X, y):
    info = {}
    dict = grouping(X, y)
    for classValue, instances in dict.items():
        info[classValue] = mean_StdDev(instances)
    return info

In [319]:
model = fit(X_train, y_train)
model

{1: [(6.038709677419354, 0.5226071943342271),
  (2.796774193548387, 0.3341495383484685),
  (4.358064516129032, 0.4507580234437594),
  (1.3806451612903226, 0.17401025800932862)],
 0: [(5.012903225806451, 0.3896510708175294),
  (3.4290322580645163, 0.44211125929046174),
  (1.464516129032258, 0.18716906278687226),
  (0.25806451612903225, 0.11481635640850447)],
 2: [(6.589285714285716, 0.6640723330271059),
  (2.967857142857142, 0.33228008202426595),
  (5.542857142857143, 0.5808222596926683),
  (2.0535714285714284, 0.2873662559859196)]}

### Gaussian Probability

In [320]:
def gaussianProbability(x, mean, stdev):
    exp = math.exp(-(math.pow(x - mean, 2) / (2 * math.pow(stdev, 2))))
    return (1 / (math.sqrt(2 * math.pi) * stdev)) * exp

### Predict best choice class for given data

In [321]:
def predict_class(model, X_test):
    probabilities = {}
    for classValue, classSummaries in model.items():
        probabilities[classValue] = 1
        for i in range(len(classSummaries)):
            mean, std_dev = classSummaries[i]
            x = X_test[i]
            probabilities[classValue] *= gaussianProbability(x, mean, std_dev)

    print(probabilities)
    
    bestLabel, bestProb = None, -1
    for classValue, probability in probabilities.items():
        if bestLabel is None or probability > bestProb:
            bestProb = probability
            bestLabel = classValue
    return bestLabel


def getPredictions(model, X_test):
    predictions = []
    for i in range(len(X_test)):
        result = predict_class(model, X_test[i])
        predictions.append(result)
    return predictions

In [322]:
y_pred = getPredictions(model, X_test)
print("\nModel predictions are: \n", [int(x) for x in y_pred])

{1: 1.8060822276706276e-21, 0: 5.462796239955406, 2: 1.27740263586374e-22}
{1: 6.424345628667327e-21, 0: 3.397338902501419, 2: 2.2294522383823646e-22}
{1: 5.201815356494369e-21, 0: 2.557086987647903, 2: 1.9924043007321037e-22}
{1: 6.405401838430352e-22, 0: 5.261973896265119, 2: 5.31805670657755e-23}
{1: 1.5394856143265735e-20, 0: 3.432845492171532, 2: 2.443775154950065e-22}
{1: 9.444589813569704e-21, 0: 5.897673405537695, 2: 4.691176754731315e-22}
{1: 1.6340101971470403e-20, 0: 3.9821345302557196, 2: 7.121602331483383e-22}
{1: 7.140288453962278e-23, 0: 1.3444148240053078, 2: 1.4989971307554855e-23}
{1: 4.754294354984934e-26, 0: 0.04663093303396689, 2: 3.26374670056356e-26}
{1: 2.2562229683536518e-18, 0: 2.530065479107858, 2: 9.558012030958185e-21}
{1: 1.0462620751831757e-20, 0: 5.20229463484479, 2: 5.9561529673607055e-22}
{1: 4.488813234276169e-21, 0: 5.044964377454338, 2: 2.7398061793658597e-22}
{1: 4.060200053604364e-17, 0: 1.906796776177129, 2: 1.1561211787296958e-19}
{1: 1.21237068

### Calculate accuracy of the model

In [323]:
def accuracy_rate(y_test, y_pred):
    correct = 0
    for i in range(len(y_test)):
        if y_test[i] == y_pred[i]:
            correct += 1
    return (correct / float(len(y_test))) * 100.0

def confusion_mtx(y_test, y_pred):
    mtx = [ [ 0 for i in range(3) ] for j in range(3) ]
    for i in range(len(y_test)):
        mtx[int(y_test[i])][int(y_pred[i])] += 1
    return mtx

In [324]:
accuracy = accuracy_rate(y_test, y_pred)
confusion = confusion_mtx(y_test, y_pred)
print("Accuracy of model is: ", accuracy)
print("Confusion of model is: \n", pd.DataFrame(confusion))

Accuracy of model is:  96.66666666666667
Confusion of model is: 
     0   1   2
0  19   0   0
1   0  18   1
2   0   1  21


<hr>

### NAIVE BAYES (USING SKLEARN LIBRARY)

### Import libraries

In [325]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

### Functionality

In [326]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size=0.4, random_state=0)
gnb = GaussianNB()
y_pred2 = gnb.fit(X_train2, y_train2).predict(X_test2)
acc_score = accuracy_score(y_test2, y_pred2)
conf_mat = confusion_matrix(
        y_test2, y_pred2, labels = [0., 1., 2.])
print("Accuracy of model is: ", acc_score)
print("Confusion matrix of model is: \n", conf_mat)

Accuracy of model is:  0.9333333333333333
Confusion matrix of model is: 
 [[16  0  0]
 [ 0 23  0]
 [ 0  4 17]]


<hr>

### OPTIMAL BAYES (SELF-DEVELOPED)

In [327]:
import operator

In [328]:
def mu(X, y):
    mu_dict = {}
    groups = grouping(X, y)
    for id, group in groups.items():
        mu_dict[id] = [np.mean(np.array(group), axis=0)]
    return mu_dict

def sigma(X, y):
    sigma_dict = {}
    groups = grouping(X, y)
    for id, group in groups.items():
        df = pd.DataFrame(group)
        cov = df.cov().to_numpy()
        sigma_dict[id] = cov
    return sigma_dict

In [329]:
def optimal_fit(X_train, y_train):
    info = {}
    info["sigma"] = sigma(X_train, y_train)
    info["mu"] = mu(X_train, y_train)
    return info

In [330]:
model = optimal_fit(X_train, y_train)
model

{'sigma': {1: array([[0.27311828, 0.08312903, 0.16267742, 0.04344086],
         [0.08312903, 0.11165591, 0.07219355, 0.03493548],
         [0.16267742, 0.07219355, 0.2031828 , 0.06382796],
         [0.04344086, 0.03493548, 0.06382796, 0.03027957]]),
  0: array([[0.15182796, 0.13594624, 0.01813978, 0.01089247],
         [0.13594624, 0.19546237, 0.00573118, 0.00992473],
         [0.01813978, 0.00573118, 0.03503226, 0.0047957 ],
         [0.01089247, 0.00992473, 0.0047957 , 0.0131828 ]]),
  2: array([[0.44099206, 0.09297619, 0.34084656, 0.07578042],
         [0.09297619, 0.11041005, 0.06253968, 0.04771164],
         [0.34084656, 0.06253968, 0.3373545 , 0.06613757],
         [0.07578042, 0.04771164, 0.06613757, 0.08257937]])},
 'mu': {1: [array([6.03870968, 2.79677419, 4.35806452, 1.38064516])],
  0: [array([5.01290323, 3.42903226, 1.46451613, 0.25806452])],
  2: [array([6.58928571, 2.96785714, 5.54285714, 2.05357143])]}}

In [331]:
def optimal_predict(model, vector):
    mus = model['mu']
    sigmas = model['sigma']
    best_label = -1
    best_probability = -1
    for id, mu_group in mus.items():
        det = np.linalg.det(sigmas[id]) 
        denominator = math.sqrt(2 * math.pi * det)
        sub = np.subtract(vector, mu_group)
        numerator = math.exp((-0.5)*np.matmul(np.matmul(sub, np.linalg.inv(sigmas[id])), sub.transpose()))
        f = numerator / denominator
        if f > best_probability:
            best_label = id
            best_probability = f
    return best_label

In [332]:
def get_optimal_prediction(model, X_test):
    y_pred = []
    for vec in X_test:
        y_pred.append(optimal_predict(model, vec))
    return y_pred

In [333]:
y_pred3 = get_optimal_prediction(model, X_test)
y_pred3

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [334]:
accuracy3 = accuracy_rate(y_test, y_pred3)
confusion3 = confusion_mtx(y_test, y_pred3)
print("Accuracy of model is: ", accuracy)
print("Confusion of model is: \n", pd.DataFrame(confusion))

Accuracy of model is:  96.66666666666667
Confusion of model is: 
     0   1   2
0  19   0   0
1   0  18   1
2   0   1  21
